# Pre-commit configuration for GPU PostgreSQL Parser
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3
        args: ['--line-length=100']

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ['--profile', 'black', '--line-length=100']

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ['--max-line-length=100', '--extend-ignore=E203,W503']

  # Pytest hooks - commented out for now to allow commits with failing tests
  # Uncomment when you want to enforce test passing before commit
  
  # - repo: local
  #   hooks:
  #     - id: pytest-check
  #       name: pytest
  #       entry: bash -c 'pytest tests/ -v --tb=short --maxfail=1 || exit 1'
  #       language: system
  #       types: [python]
  #       pass_filenames: false
  #       always_run: true
  #       stages: [pre-commit]

  #     - id: pytest-quick
  #       name: pytest-quick
  #       entry: bash -c 'pytest tests/ -v --tb=short --maxfail=1 -m "not slow" || exit 1'
  #       language: system
  #       types: [python]
  #       pass_filenames: false
  #       stages: [pre-push]